apiVersion: config.openshift.io/v1
kind: Proxy
metadata:
  name: cluster
spec:
{% if proxy_http_url is defined and proxy_http_url != '' %}
  httpProxy: "{{ proxy_http_url }}"
{% endif %}
{% if proxy_https_url is defined and proxy_https_url != '' %}
  httpsProxy: "{{ proxy_https_url }}"
{% endif %}
{% if proxy_no_proxy_list is defined and proxy_no_proxy_list | length > 0 %}
  noProxy: "{{ proxy_no_proxy_list | join(',') }}"
{% endif %}
{% if lookup('file', '../certs/ca-bundle.crt', errors='ignore') != '' %}
  trustedCA:
    name: user-ca-bundle
{% endif %}